services:
  nginx:
    container_name: nginx
    image: 'api.repoflow.io/desiderati/docker/library/nginx:1.25.5.2'
    ports:
      - '80:80'
      - '81:81'

    environment:
      - GVAR_HELLO_WORLD_MSG=Oie, Tudo bem?

    volumes:
      # Uncomment the following line if you want to use a custom configuration.
      - ./nginx.server-default.conf:/etc/nginx/conf.d/nginx.server-default.conf
      - ./logs/nginx/:/var/log/nginx/
      - ./www/:/opt/www/
